In [29]:
import pandas as pd

orders = pd.DataFrame({
    "order_id": [1,2,3,4,5,6],
    "user_id": [10,10,11,12,11,10],
    "amount": [100,200,150,300,120,80],
    "city": ["Moscow","Moscow","SPB","Kazan","SPB","Moscow"]
})

result = (
    orders
    .groupby("city")
    .agg(
        orders_cnt=("order_id", "count"),
        total_amount=("amount", "sum"),
        avg_amount=("amount", "mean")
    )
    .reset_index()
    .sort_values("total_amount", ascending=False)
)

result

     city  orders_cnt  total_amount  avg_amount
1  Moscow           3           380  126.666667
0   Kazan           1           300  300.000000
2     SPB           2           270  135.000000

In [31]:
users = pd.DataFrame({
    "user_id": [10,11,12],
    "segment": ["premium", "mass", "premium"]
})

result = orders.merge(users, on="user_id", how="left")
result

   order_id  user_id  amount    city  segment
0         1       10     100  Moscow  premium
1         2       10     200  Moscow  premium
2         3       11     150     SPB     mass
3         4       12     300   Kazan  premium
4         5       11     120     SPB     mass
5         6       10      80  Moscow  premium

In [32]:
texts = ["a", "b", "a", "c", "b", "a"]

freq = {}

for x in texts:
    freq[x] = freq.get(x, 0) + 1

freq

{'a': 3, 'b': 2, 'c': 1}

In [33]:
from collections import Counter

Counter(texts)

Counter({'a': 3, 'b': 2, 'c': 1})

In [34]:
s = " Клиент хочет открыть вклад Premium "

clean = s.strip().lower()
words = clean.split()

clean, words

('клиент хочет открыть вклад premium',
 ['клиент', 'хочет', 'открыть', 'вклад', 'premium'])

In [36]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score

data = load_breast_cancer()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=43
)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

pred = model.predict(X_test)

f1_score(y_test, pred)

/Users/amadey/devwork/anton/mczk/.venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.9866666666666667

In [39]:
import pandas as pd

orders = pd.DataFrame({
    "user_id": [1,1,2,3,2,1],
    "amount": [100,200,150,300,50,80]
})

result = (
    orders
    .groupby("user_id")
    .agg(total_amount=("amount", "sum"))
    .reset_index()
    .sort_values("total_amount", ascending=False)
    .head(1)
)

result

   user_id  total_amount
0        1           380

In [48]:
sales = pd.DataFrame({
    "city": ["Moscow", "SPB", "Moscoow", "Kazan"],
    "amount": [100, 200, 150, 300]
})

result = (
    sales
    .groupby("city")
    .agg(avg_amount=("amount", "mean"))
    .reset_index()
)

result

      city  avg_amount
0    Kazan       300.0
1  Moscoow       150.0
2   Moscow       100.0
3      SPB       200.0

In [52]:
result = sales[sales["amount"] > 150]

result

    city  amount
1    SPB     200
3  Kazan     300

In [54]:
sales["double_amount"] = sales["amount"] * 2

sales

      city  amount  double_amount
0   Moscow     100            200
1      SPB     200            400
2  Moscoow     150            300
3    Kazan     300            600

In [62]:
sales["date"] = ["2025-01-01", "2025-01-02", "2025-02-01", "2025-02-03"]

sales["date"] = pd.to_datetime(sales["date"])
sales["month"] = sales["date"].dt.month

sales["month"]

0    1
1    1
2    2
3    2
Name: month, dtype: int32

In [59]:
sales.columns

Index(['city', 'amount', 'double_amount', 'date', 'month'], dtype='str')

In [69]:
users = pd.DataFrame({
    "user_id": [1,2,3],
    "segment": ["A","B","A"]
})

orders.merge(users, on="user_id", how="left")

   user_id  amount segment
0        1     100       A
1        1     200       A
2        2     150       B
3        3     300       A
4        2      50       B
5        1      80       A

In [66]:
import pandas as pd

df = pd.DataFrame({
    "city": ["Moscow", "Moscow", "SPB"],
    "product": ["Phone", "TV", "Phone"],
    "sales": [100, 200, 150]
})

pivot_df = df.pivot(
    index="city",
    columns="product",
    values="sales"
)

pivot_df

product  Phone     TV
city
Moscow   100.0  200.0
SPB      150.0    NaN

In [68]:
df.pivot_table(
    index="city",
    columns="product",
    values="sales",
    aggfunc="sum"
)

product  Phone     TV
city
Moscow   100.0  200.0
SPB      150.0    NaN

In [73]:
from sklearn.metrics import roc_auc_score

y_probs = model.predict_proba(X_test)[:, 1]

roc_auc_score(y_test, y_probs)

0.9911111111111112

In [ ]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    person1 = Person("Jonh", 30)
    person2 = Person("Alice", 25)
    print(person1, name, age)
    print(person2, name, age)

In [ ]:
def my_function(my_list=None):
    if my_list is None:
        my_list = []
        # do something with my_list
        pass

In [113]:
# classmethod

class MyClass:
    def __init__(self, value):
        self._value = value

        @classmethod
        def from_string(cls, input_string):
            value = process_input_string(input_string)

In [ ]:
import asyncio

async def hello():
    await asyncio.sleep(1)
    print("Hello")

async def world():
    await asyncio.sleep(2)
    print("World")

async def main():
    await asyncio.gather(hello(), world())

if __name__ == '__main__':
    asyncio.run.(main())

In [74]:
my_list = [1, 2, 3, 4, 5]
# get an iterator from the list
my_iterator = iter(my_list)
# we output the elements of the iterator
print(next(my_iterator)) 
print(next(my_iterator)) 
print(next(my_iterator))

1
2
3

In [75]:
def my_generator():
    yield 1
    yield 2
    yield 3
    yield 4
    yield 5

my_iterator = my_generator()

print(next(my_iterator))
print(next(my_iterator))
print(next(my_iterator))
print(next(my_iterator))
print(next(my_iterator))

1
2
3
4
5

In [77]:
def my_generator(n):
    for i in range(n + 1):
        yield i

my_gen = my_generator(5)
for i in my_gen:
    print(i)

0
1
2
3
4
5

In [80]:
class MyIterator:
    def __init__(self, data):
        self.index = 0
        self.data = data

    def __iter__(self):
        return self

    def __next__(self):
        if self.index >= len(self.data):
            raise StopIteration
        result = self.data[self.index]
        self.index += 1
        return result

In [86]:
with open('data.txt', 'r') as f:
    data = f.read()

print(data)

0
1
2
3
4
5

In [88]:
import copy
old_list = data

new_list = old_list.copy()
new_list = copy.deepcopy(old_list)

AttributeError: 'str' object has no attribute 'copy'

In [89]:
global_var = 42
def my_func():
    global global_var
    print(global_var)

my_func()

42

In [96]:
# slots atribute

class Person:
    __slots__ = ['name', 'age']
    def __init__(self, name, age):
        self.name = name
        self.age = age

In [98]:
class MyMeta(type):
    def __new__(cls, name, bases, dct):
        dct['my_attribute'] = 42
        return super(MyMeta, cls).__new__(cls, name, bases, dct)

class MyClass(metaclass=MyMeta):
    pass

print(MyClass.my_attribute)

42

In [99]:
import pdb
pdb.set_trace()

--Call--
> /Users/amadey/devwork/anton/mczk/.venv/lib/python3.12/site-packages/IPython/core/displayhook.py(269)__call__()
    267         self._is_active = False
    268
--> 269     def __call__(self, result=None):
    270         """Printing with history cache management.
    271

ipdb>  q

In [100]:
class MyClass:
    x = 42
    def foo(self):
        return self.x

In [103]:
# create equael class without key word class
MyClass = type('MyClass', (), {'x': 42, 'foo': lambda self: self.x})

In [106]:
from importlib import reload
import my_module
reload(my_module)

ModuleNotFoundError: No module named 'my_module'

In [108]:
# decorator that hendle errors and repeat function N times

import functools
def retry(func):
    @functionals.wraps(func)
    def wrapper(*args, **kwargs):
        max_retries = 3
        for i in range(max_retries):
            try:
                result = func(*args, **kwargs)
                return result
            except Exceptions as e:
                print(f'Error occured: {e}. Retrying ({i+1}/{max_retries})...')
            raise Exception(f'Function {func.__name__} failed after {max_retries} attempts.')
    return wrapper

    @retry 
    def my_function(arg1, arg2):
        pass

In [109]:
len(' '.join(list(map(str, [0, 1]))))

3

In [110]:
# multiple inheritance
class MyBaseClass1:
    pass

class MyBaseClass2:
    pass

class MyDerivedClass(MyBaseClass1, MyBaseClass2):
    pass

In [112]:
class Parent1:
    def method1(self):
        print("This is a method from Parent1")

class Parent2:
    def method2(self):
        print("This is a method from Parent2")

class MyClass(Parent1, Parent2):
    pass

obj = MyClass()
obj.method1() # output "This is a method from Parent1"
obj.method2() # output "This is a method from Parent2"

This is a method from Parent1
This is a method from Parent2